name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.9b8794df-032f-48f8-8e99-258d12a288c0 }}
        with:
          command: npm run test:cloud

